# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20161019_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
