# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20161019_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default='Johanderson', max_length=100),
        ),
    ]
