# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20161020_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(default='', max_length=100),
        ),
    ]
