# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='phone'),
        ),
    ]
